[build]
  publish = "."
  command = "echo 'Static site - no build required'"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.json"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Content-Type = "application/json; charset=utf-8"

[[redirects]]
  from = "/generator"
  to = "/#generator"
  status = 301

[[redirects]]
  from = "/guide"
  to = "/#understanding-mailto"
  status = 301

[[redirects]]
  from = "/tutorial"
  to = "/#understanding-mailto"
  status = 301

# Redirect old domain references (if any)
[[redirects]]
  from = "https://mailtolinkgenerator.pro/*"
  to = "https://mailtogenpro.com/:splat"
  status = 301
  force = true

# 404 fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
